image: node:10.15.3
pipelines:
  branches:
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - npm install -g firebase-tools
            - npm ci
            - firebase deploy --token=$FIREBASE_TOKEN --project pataphysical-99efa --non-interactive
